var searchData=
[
  ['implementation_0',['Implementation',['../compare_tcp.html#compare2',1,'2.0 TCP Implementation'],['../compare_tcp.html#file_tcp_link',1,'2.1 Files for TCP implementation'],['../compare_tcp.html#tcpTest2',1,'4.2 Make sure that the TCP instance and our protocol get half as much throughput as our implementation.']]],
  ['implementation_20vs_20tcp_1',['Our implementation vs TCP',['../compare_tcp.html',1,'main_test_page']]],
  ['important_20notes_2',['Important Notes',['../competing.html#test4',1,'3.4 Important Notes'],['../compare_tcp.html#tcpTest4',1,'4.3 Important Notes']]],
  ['inctances_20of_20the_20protocol_20should_20occur_20within_20100_20rtts_3',['3.3 The convergence of throughput between the 2 inctances of the protocol should occur within 100 RTTs',['../competing.html#test3',1,'']]],
  ['instance_20and_20our_20protocol_20get_20half_20as_20much_20throughput_20as_20our_20implementation_4',['4.2 Make sure that the TCP instance and our protocol get half as much throughput as our implementation.',['../compare_tcp.html#tcpTest2',1,'']]],
  ['instance_20key_20requirements_5',['Single Instance -  Key Requirements',['../packet_loss.html#packet_loss_2_1_1',1,'']]],
  ['instance_20of_20a_20protocol_6',['Instance of A Protocol',['../bandwidth_and_throughput.html#b_and_t1',1,'1.0 Throughput For A Single Instance of A Protocol'],['../bandwidth_and_throughput.html#b_and_t2',1,'2.0 Bandwidth For A Single Instance of A Protocol']]],
  ['instance_20of_20our_20protocol_7',['Instance of Our Protocol',['../packet_loss.html#packet_loss_2_1',1,'2.1 Testing a Single Instance of Our Protocol'],['../individual.html',1,'Testing a Single Instance of Our Protocol']]],
  ['instance_20of_20tcp_20competing_20with_20our_20protocol_20on_20the_20same_20private_20network_8',['4.1 Have an instance of TCP competing with our protocol on the same private network.',['../compare_tcp.html#tcpTest1',1,'']]],
  ['instance_20results_9',['Single Instance - Results',['../packet_loss.html#packet_loss_2_1_3',1,'']]],
  ['instance_20usage_20instructions_10',['Single Instance - Usage Instructions',['../packet_loss.html#packet_loss_2_1_2',1,'']]],
  ['instances_11',['Multiple Competing Instances',['../competing.html',1,'main_test_page']]],
  ['instances_20key_20requirements_12',['Competing Instances -  Key Requirements',['../packet_loss.html#packet_loss_2_2_1',1,'']]],
  ['instances_20of_20our_20protocol_13',['2.2 Testing a Competing Instances of Our Protocol',['../packet_loss.html#packet_loss_2_2',1,'']]],
  ['instances_20of_20our_20protocol_20at_20roughly_20the_20same_20time_14',['3.1 Start two instances of our protocol at roughly the same time',['../competing.html#test1',1,'']]],
  ['instances_20results_15',['Competing Instances - Results',['../packet_loss.html#packet_loss_2_2_3',1,'']]],
  ['instances_20they_20should_20be_20the_20same_2010_16',['3.2 After measuring the throughput of both instances, they should be the same +/- 10%',['../competing.html#test2',1,'']]],
  ['instances_20usage_20instructions_17',['Competing Instances - Usage Instructions',['../packet_loss.html#packet_loss_2_2_2',1,'']]],
  ['instructions_18',['Instructions',['../individual.html#individual_3',1,'3.0 Testing Expectation 3 - Usage Instructions'],['../compare_tcp.html#tcp_4',1,'4.0 Testing Expectation 4 - Usage Instructions'],['../competing.html#mci_4',1,'4.0 Testing Expectation 4 - Usage Instructions'],['../packet_loss.html#packet_loss_2_2_2',1,'Competing Instances - Usage Instructions'],['../packet_loss.html#packet_loss_2_1_2',1,'Single Instance - Usage Instructions']]],
  ['introduction_19',['Introduction',['../index.html#sec1',1,'1.0 Introduction'],['../main_test_page.html#intro_sec',1,'Introduction']]],
  ['is_5fack_20',['IS_ACK',['../packet__header_8h.html#a738f54051837b67b88c5ded16da668da',1,'packet_header.h']]],
  ['is_5flast_5fpacket_21',['IS_LAST_PACKET',['../packet__header_8h.html#af0fbde21f35835770e31f7dc8d6f0350',1,'packet_header.h']]],
  ['isflagset_22',['isFlagSet',['../packet__header_8h.html#abad6283ef4e91e8a99d9c0784ae4f1a9',1,'packet_header.h']]]
];
